import { CampaignBanner } from "@/components/campaign-banner";
import { CommunityAiSummary } from "@/components/community-ai-summary";
import { HouseholdSelector } from "@/components/household-selector";
import { PeerComparisonView } from "@/components/peer-comparison-view";
import { getCommunity, getProfiles, getSnapshots, pickHousehold } from "@/lib/data";

export default async function CommunityPage({ searchParams }: { searchParams: Promise<{ household?: string }> }) {
  const params = await searchParams; const profiles = getProfiles(); const householdId = pickHousehold(params.household);
  const profile = profiles.find((item) => item.household_id === householdId)!; const snapshot = getSnapshots().find((item) => item.household_id === householdId)!; const matched = getCommunity().matched_comparison[householdId];
  return <div className="space-y-6"><HouseholdSelector profiles={profiles.slice(0, 5)} selectedId={householdId} /><section className="card p-5"><p className="text-xs font-semibold uppercase tracking-wider text-water-600">Private, relevant context</p><h1 className="mt-1 text-2xl font-semibold text-water-700">My Community</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-600">Compare your use with genuinely similar households—not broad districts. Learn what good performance can look like, join voluntary campaigns and understand why collective water choices matter.</p></section><CommunityAiSummary householdId={householdId} /><PeerComparisonView profile={profile} matched={matched} userLppd={snapshot.litres_per_person_day} /><CampaignBanner weeklyChange={snapshot.week_change_pct} /><section className="grid gap-4 md:grid-cols-3"><Awareness icon="💧" title="Every drop has a journey" text="Drinking water must be captured, treated, tested and transported before it reaches your tap." /><Awareness icon="⚡" title="Water also uses energy" text="Moving and treating water consumes energy, so efficient use can reduce pressure on both systems." /><Awareness icon="🌿" title="Prepare for dry periods" text="Steady habits built before water stress are easier and fairer than sudden restrictions." /></section></div>;
}
function Awareness({ icon, title, text }: { icon: string; title: string; text: string }) { return <article className="card p-5"><span className="text-3xl" aria-hidden="true">{icon}</span><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
